DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS article;


CREATE TABLE users (
   id SERIAL PRIMARY KEY,
   username VARCHAR NOT NULL UNIQUE,
   password VARCHAR NOT NULL,
   date_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE article (
   id SERIAL PRIMARY KEY,
   title VARCHAR(225) NOT NULL,
   content TEXT NOT NUll,
   users_id  INT NOT NULL,
   date_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
